version: '3.5'

services:
  shinyproxy:
    build: ./shinyproxy
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - sp-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx: 
    image: nginx:1.17.5
    restart: unless-stopped
    ports:
      - 4848:80
    networks:
      - sp-net
    depends_on:
      - shinyproxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  sp-net:

