version: '3.5'

services:
  cyanus:
    image: quirinmanz/cyanus:latest
    restart: unless-stopped
    ports:
      - 3838:3838
    networks:
      - sp-net
    volumes:
      - ./data:/srv/cytof_pipeline/data
      #- ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
  shinyproxy:
    build: ./shinyproxy
    restart: unless-stopped
    depends_on: 
      - cyanus
    expose:
      - 8080
    networks:
      - sp-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx: 
    image: nginx:1.17.5
    restart: unless-stopped
    ports:
      - 4848:80
    networks:
      - sp-net
    depends_on:
      - shinyproxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  sp-net:

