proxy:
  port: 8080
  landing-page: /app/cyanus-dev
  favicon-path: ./favicon.png
  authentication: none
  admin-groups: admins
  container-log-path: ./container-logs
  container-backend: docker
  container-wait-time: 10000
  port-range-start: 20000
  port-range-max: 20049
  heartbeat-rate: 10000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 3600000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  hide-navbar: true
  users:
  - name: jack
    password: password
    groups: admins
  docker:
    internal-networking: true
  specs:
    - id: cyanus-dev
      display-name: CYANUS 2.0
      description: CYtometry ANalysis Using Shiny 2.0
      container-cmd: ["R", "-e", "shiny::runApp(host='0.0.0.0', port=3838)"]
      container-network: cyanus-dev_sp-net
      container-image: judithbernett/cyanus:2.0
      

logging:
  file:
    name: shinyproxy.log
  level:
    root: DEBUG

server:
  useForwardHeaders: true
