proxy:
  port: 8080
  landing-page: /app/cyanus
  favicon-path: favicon.ico
  authentication: none
  admin-groups: admins
  container-log-path: ./container-logs
  container-backend: docker
  container-wait-time: 10000
  heartbeat-rate: 10000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 3600000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  hide-navbar: true
  users:
  - name: jack
    password: password
    groups: admins
  docker:
    internal-networking: true
  specs:
    - id: cyanus
      display-name: CYANUS
      description: CYtometry ANalysis Using Shiny
      container-cmd: ["R", "-e", "shiny::runApp(host='0.0.0.0', port=3838)"]
      container-network: cyanus_sp-net
      container-image: quirinmanz/cyanus:latest

logging:
  file:
    name: shinyproxy.log
  level:
    root: DEBUG

server:
  useForwardHeaders: true
